(ns dev.static-viz-font-widths
  "Generate the per-character advance width table that static viz uses to measure text.

  Static viz renders SVG in a headless GraalVM context, so it cannot measure text with a real font. Upstream
  ships a precomputed table for Lato ([[frontend/src/metabase/static-viz/constants/char-sizes.ts]]); this fork
  renders in Poppins (see README-TEAL.md), which is ~9% wider, so it needs a table of its own or every axis
  margin, label truncation and legend layout is computed too small.

  Regenerate after changing the Poppins asset:

    clj -M:dev -m dev.static-viz-font-widths

  Widths are advance widths in px at [[base-font-size]] and weight 400, matching `CHAR_SIZES_FONT_SIZE` /
  `CHAR_SIZES_FONT_WEIGHT`. Characters the font cannot display are omitted — `measureTextWidth` falls back to
  the Lato table for those."
  (:require
   [clojure.java.io :as io]
   [clojure.string :as str])
  (:import
   (java.awt Font)
   (java.awt.font FontRenderContext)))

(set! *warn-on-reflection* true)

(def ^:private font-resource "frontend_client/app/fonts/Poppins/Poppins-Regular.ttf")

(def ^:private output-path "frontend/src/metabase/static-viz/constants/poppins-char-widths.ts")

(def ^:private base-font-size
  "Must match `CHAR_SIZES_FONT_SIZE` in frontend/src/metabase/static-viz/constants/char-sizes.ts."
  10.0)

(def ^:private char-ranges
  "The scripts Poppins covers that we care about for chart labels: printable ASCII, Latin-1 Supplement and
  Latin Extended-A. Poppins also has Devanagari, but those glyphs need shaping rather than per-character
  advances, so they are left to the Lato fallback."
  [[0x20 0x7E]
   [0xA0 0xFF]
   [0x100 0x17F]])

(defn- load-font ^Font []
  (with-open [is (io/input-stream (io/resource font-resource))]
    (.deriveFont (Font/createFont Font/TRUETYPE_FONT is) (float base-font-size))))

(defn- char-widths
  "Map of character -> advance width in px, for every character in [[char-ranges]] the font can display."
  [^Font font]
  ;; fractional metrics on, antialiasing off: we want the unrounded advance, not a device-pixel-snapped one
  (let [frc (FontRenderContext. nil false true)]
    (into (sorted-map)
          (for [[start end] char-ranges
                code-point  (range start (inc end))
                :let  [c (char code-point)]
                :when (.canDisplay font c)]
            [c (-> (.getStringBounds font (str c) frc)
                   .getWidth
                   (* 10000.0)
                   Math/round
                   (/ 10000.0))]))))

(defn- ts-key
  "JSON-escape a character for use as an object key."
  [c]
  (case c
    \" "\\\""
    \\ "\\\\"
    (if (< (int c) 0x20)
      (format "\\u%04x" (int c))
      (str c))))

(defn- ->ts [widths]
  (str "// Generated by dev.static-viz-font-widths — do not edit by hand.\n"
       "// Regenerate with: clj -M:dev -m dev.static-viz-font-widths\n"
       "//\n"
       "// Advance widths in px for Poppins Regular at " (int base-font-size) "px / weight 400,\n"
       "// keyed by character. Used by ../lib/text.ts in place of the Lato table in\n"
       "// ./char-sizes.ts. Characters Poppins cannot display are absent and fall back\n"
       "// to the Lato measurements.\n"
       "\n"
       "export const POPPINS_CHAR_WIDTHS: Record<string, number> = {\n"
       (str/join "\n" (for [[c w] widths]
                        (format "  \"%s\": %s," (ts-key c) w)))
       "\n};\n"))

(defn -main
  "Write the Poppins width table to [[output-path]]."
  [& _args]
  (let [widths (char-widths (load-font))
        file   (io/file output-path)]
    (io/make-parents file)
    (spit file (->ts widths))
    (println (format "Wrote %d character widths to %s" (count widths) output-path))))
